ruby:
  config_file: .rubocop.yml

coffee_script:
  config_file: .coffeelint.json

javascript:
  enabled: true
  config_file: .javascript-style.json
  ignore_file: .javascript_ignore

scss:
  config_file: .scss-lint.yml

ShowCopNames: true
