scss_files: "app/assets/stylesheets/**/*.scss"
exclude: "app/assets/stylesheets/vendor/**"

linters:
  Comment:
    enabled: true
  HexNotation:
    enabled: false
  IdSelector:
    enabled: false
  Indentation:
    character: space
    width: 2
  LeadingZero:
    enabled: true
    style: include_zero
  MergeableSelector:
    enabled: true
    force_nesting: true
  NestingDepth:
    enabled: false
  PlaceholderInExtend:
    enabled: false
  PropertySortOrder:
    enabled: false
  QualifyingElement:
    enabled: false
  SelectorDepth:
    enabled: false
  SelectorFormat:
    enabled: false
  Shorthand:
    enabled: false
  SingleLinePerSelector:
    enabled: false
  SpaceAfterComma:
    enabled: false
  SpaceAfterPropertyColon:
    enabled: false
  SpaceBeforeBrace:
    enabled: false
  StringQuotes:
    enabled: false
  UnnecessaryMantissa:
    enabled: false
  VendorPrefix:
    enabled: false
  VendorPrefixes:
    enabled: false
  ZeroUnit:
    enabled: false
