# Lint config used by scss-lint locally. Hound uses .scss-style.yml
# Some linters are disabled to avoid huge amounts of linter spam, but we'll
# fix them eventually.
scss_files: "app/assets/stylesheets/**/*.scss"
exclude: "app/assets/stylesheets/vendor/**"

linters:
  Comment:
    enabled: true
  HexNotation:
    enabled: false
  IdSelector:
    enabled: false
  Indentation:
    character: space
    width: 2
  LeadingZero:
    enabled: true
    style: include_zero
  MergeableSelector:
    enabled: true
    force_nesting: true
  # Sam: I don't like that this is disabled. We should consider refactoring the scss at some point.
  NestingDepth:
    enabled: false
  PlaceholderInExtend:
    enabled: false
  # Sam: I got up to here when linting the SCSS. We should continue down this list to lint our codebase
  ColorVariable:
    enabled: false
  PropertySortOrder:
    enabled: false
  QualifyingElement:
    enabled: false
  SelectorDepth:
    enabled: false
  SelectorFormat:
    enabled: false
  Shorthand:
    enabled: false
  SingleLinePerSelector:
    enabled: false
  SpaceAfterComma:
    enabled: false
  SpaceAfterPropertyColon:
    enabled: false
  SpaceBeforeBrace:
    enabled: false
  StringQuotes:
    enabled: false
  UnnecessaryMantissa:
    enabled: false
  VendorPrefix:
    enabled: false
  VendorPrefixes:
    enabled: false
  ZeroUnit:
    enabled: false
